In [ ]:
import numpy as np
def lu_decomposition(A):
    n = len(A)
    # Initialize L and U matrices
    L = np.zeros((n, n))
    U = np.zeros((n, n))
    for i in range(n):
        # Upper Triangular Matrix
        for k in range(i, n):
            sum_upper = 0
            for j in range(i):
                sum_upper += L[i][j] * U[j][k]
            U[i][k] = A[i][k] - sum_upper
        # Lower Triangular Matrix
        L[i][i] = 1  # Diagonal as 1
        for k in range(i + 1, n):
            sum_lower = 0
            for j in range(i):
                sum_lower += L[k][j] * U[j][i]
            L[k][i] = (A[k][i] - sum_lower) / U[i][i]
    return L, U
def forward_substitution(L, b):
    n = len(L)
    y = np.zeros(n)
    for i in range(n):
        sum_value = 0
        for j in range(i):
            sum_value += L[i][j] * y[j]
        y[i] = b[i] - sum_value
    return y
def backward_substitution(U, y):
    n = len(U)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        sum_value = 0
        for j in range(i + 1, n):
            sum_value += U[i][j] * x[j]
        x[i] = (y[i] - sum_value) / U[i][i]
    return x
# Input Matrix A
A = np.array([
    [2, -1, -2],
    [-4, 6, 3],
    [-4, -2, 8]
], dtype=float)
# Constant Matrix b
b = np.array([-2, 9, -5], dtype=float)
# Perform LU Decomposition
L, U = lu_decomposition(A)
# Solve Ly = b
y = forward_substitution(L, b)
# Solve Ux = y
x = backward_substitution(U, y)
# Display Results
print("Matrix A:")
print(A)
print("\nLower Triangular Matrix L:")
print(L)
print("\nUpper Triangular Matrix U:")
print(U)
print("\nIntermediate Solution y:")
print(y)
print("\nFinal Solution x:")
print(x)


Matrix A:
[[ 2. -1. -2.]
 [-4.  6.  3.]
 [-4. -2.  8.]]

Lower Triangular Matrix L:
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-2. -1.  1.]]

Upper Triangular Matrix U:
[[ 2. -1. -2.]
 [ 0.  4. -1.]
 [ 0.  0.  3.]]

Intermediate Solution y:
[-2.  5. -4.]

Final Solution x:
[-1.875       0.91666667 -1.33333333]


In [1]:
# QR Decomposition using Gram-Schmidt Method
# Application: Solving Linear System Ax = b

import numpy as np
def qr_decomposition(A):
    n = A.shape[0]
    # Initialize Q and R matrices
    Q = np.zeros((n, n))
    R = np.zeros((n, n))
    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]
    return Q, R
def solve_qr(Q, R, b):
    # Compute Qᵀb
    y = np.dot(Q.T, b)
    # Backward substitution to solve Rx = y
    n = R.shape[0]
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        sum_value = 0
        for j in range(i + 1, n):
            sum_value += R[i, j] * x[j]

        x[i] = (y[i] - sum_value) / R[i, i]
    return x
# Input Matrix A
A = np.array([
    [1, 1, 0],
    [1, 0, 1],
    [0, 1, 1]
], dtype=float)
# Constant Matrix b
b = np.array([4, 5, 6], dtype=float)
# Perform QR Decomposition
Q, R = qr_decomposition(A)
# Solve system using QR decomposition
x = solve_qr(Q, R, b)
# Display Results
print("Matrix A:")
print(A)
print("\nOrthogonal Matrix Q:")
print(Q)
print("\nUpper Triangular Matrix R:")
print(R)
print("\nSolution Vector x:")
print(x)


Matrix A:
[[1. 1. 0.]
 [1. 0. 1.]
 [0. 1. 1.]]

Orthogonal Matrix Q:
[[ 0.70710678  0.40824829 -0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.          0.81649658  0.57735027]]

Upper Triangular Matrix R:
[[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]

Solution Vector x:
[1.5 2.5 3.5]


In [ ]:
# Bernoulli Distribution
# Application: Student Exam Pass/Fail Analysis

from scipy.stats import bernoulli

print("----- Bernoulli Distribution -----")

# Probability of passing
p = 0.7

# Generate random outcomes for 10 students
# 1 = Pass, 0 = Fail
bernoulli_samples = bernoulli.rvs(p, size=10)

print("Probability of Passing:", p)
print("Student Outcomes (1=Pass, 0=Fail):")
print(bernoulli_samples)

# Probability of success
print("\nProbability of Pass:")
print(bernoulli.pmf(1, p))

# Probability of failure
print("Probability of Fail:")
print(bernoulli.pmf(0, p))

In [ ]:
# Binomial Distribution
# Application: Student Exam Pass/Fail Analysis

from scipy.stats import binom

print("----- Binomial Distribution -----")

# Number of students
n = 10

# Probability of passing
p = 0.7

# Exactly 8 students pass
k = 8

# Calculate probability
binomial_probability = binom.pmf(k, n, p)

print("Number of Students:", n)
print("Probability of Passing:", p)

print(f"\nProbability that exactly {k} students pass:")
print(binomial_probability)

# Random experiment (5 trials)
random_binomial = binom.rvs(n, p, size=5)

print("\nRandom Binomial Outcomes:")
print(random_binomial)

In [ ]:
# Z-Test
# Application: Student Performance Analysis

import numpy as np
from statsmodels.stats.weightstats import ztest

print("----- Z-Test -----")

# Sample marks
sample_marks = np.array([78, 82, 85, 88, 90, 76, 95, 89, 84, 91])

# Population mean
population_mean = 80

# Perform Z-test
z_stat, p_value = ztest(sample_marks, value=population_mean)

print("Sample Marks:")
print(sample_marks)

print("\nPopulation Mean:", population_mean)
print("\nZ-Statistic:", round(z_stat, 3))
print("P-Value:", round(p_value, 4))

alpha = 0.05

if p_value < alpha:
    print("\nResult: Reject Null Hypothesis")
else:
    print("\nResult: Fail to Reject Null Hypothesis")

In [ ]:
# Independent t-Test
# Application: Student Performance Analysis

import numpy as np
from scipy import stats

print("----- Independent t-Test -----")

# Marks of two classes
class_A = np.array([78, 82, 85, 88, 90])
class_B = np.array([72, 75, 70, 68, 74])

# Perform Independent t-test
t_stat, p_value = stats.ttest_ind(class_A, class_B)

print("Class A Marks:")
print(class_A)

print("\nClass B Marks:")
print(class_B)

print("\nt-Statistic:", round(t_stat, 2))
print("P-Value:", round(p_value, 4))

alpha = 0.05

if p_value < alpha:
    print("\nResult: Reject Null Hypothesis")
else:
    print("\nResult: Fail to Reject Null Hypothesis")

In [ ]:
# Linear Regression
# Application: House Price Prediction

import numpy as np
from sklearn.linear_model import LinearRegression

print("----- Linear Regression -----")

# Training Data
# House Size (sq.ft)
X_linear = np.array([
    [1000],
    [1200],
    [1500],
    [1800],
    [2000]
])

# House Prices (Lakhs)
y_linear = np.array([
    50,
    55,
    65,
    80,
    90
])

# Create Model
linear_model = LinearRegression()

# Train Model
linear_model.fit(X_linear, y_linear)

# Predict Price for New House
new_house_size = np.array([[1700]])
predicted_price = linear_model.predict(new_house_size)

print("Training House Sizes:")
print(X_linear.flatten())

print("\nTraining House Prices:")
print(y_linear)

print("\nPredicted Price for 1700 sq.ft house:")
print(predicted_price[0])

In [ ]:
# Logistic Regression
# Application: House Purchase Classification

import numpy as np
from sklearn.linear_model import LogisticRegression

print("----- Logistic Regression -----")

# Training Data
# House Prices (Lakhs)
X_logistic = np.array([
    [40],
    [50],
    [60],
    [70],
    [80],
    [90]
])

# Labels
# 0 = Not Purchased
# 1 = Purchased
y_logistic = np.array([
    0,
    0,
    0,
    1,
    1,
    1
])

# Create Model
logistic_model = LogisticRegression()

# Train Model
logistic_model.fit(X_logistic, y_logistic)

# Test House Price
test_price = np.array([[75]])

# Prediction
purchase_prediction = logistic_model.predict(test_price)

# Probability
purchase_probability = logistic_model.predict_proba(test_price)

print("Training House Prices:")
print(X_logistic.flatten())

print("\nPurchase Labels:")
print(y_logistic)

print("\nTest House Price:")
print(test_price[0][0])

print("\nPurchase Prediction:")
print(purchase_prediction[0])

print("\nPrediction Probabilities:")
print(purchase_probability)

In [ ]:
# Decision Tree Classification
# Application: Student Pass/Fail Prediction

import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

print("----- Decision Tree Classification -----")

# Training Data
# Features: [Study Hours, Attendance Percentage]
X = np.array([
    [2, 50],
    [3, 60],
    [4, 65],
    [5, 70],
    [6, 75],
    [7, 80],
    [8, 85],
    [9, 90]
])

# Labels
# 0 = Fail
# 1 = Pass
y = np.array([0, 0, 0, 1, 1, 1, 1, 1])

# Train Model
model = DecisionTreeClassifier(random_state=42)
model.fit(X, y)

# Test Data
X_test = np.array([
    [3, 55],
    [5, 72],
    [8, 88],
    [4, 60]
])

# Actual Labels
y_test = np.array([0, 1, 1, 0])

# Predictions
y_pred = model.predict(X_test)

# Performance Metrics
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

# Display Results
print("\nActual Labels:")
print(y_test)

print("\nPredicted Labels:")
print(y_pred)

print("\nConfusion Matrix:")
print(cm)

print("\nAccuracy:", accuracy)
print("Error Rate:", error_rate)
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

In [ ]:
# K-Nearest Neighbors (KNN)
# Application: Student Pass/Fail Prediction

import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

print("----- K-Nearest Neighbors -----")

# Training Data
X_train = np.array([
    [2, 50],
    [3, 60],
    [4, 65],
    [5, 70],
    [6, 75],
    [7, 80],
    [8, 85],
    [9, 90]
])

# Labels
y_train = np.array([0, 0, 0, 1, 1, 1, 1, 1])

# Create KNN Model
model = KNeighborsClassifier(n_neighbors=3)

# Train Model
model.fit(X_train, y_train)

# Test Data
X_test = np.array([
    [3, 55],
    [5, 72],
    [8, 88],
    [4, 60]
])

# Actual Labels
y_test = np.array([0, 1, 1, 0])

# Predictions
y_pred = model.predict(X_test)

# Performance Metrics
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

# Display Results
print("\nActual Labels:")
print(y_test)

print("\nPredicted Labels:")
print(y_pred)

print("\nConfusion Matrix:")
print(cm)

print("\nAccuracy:", accuracy)
print("Error Rate:", error_rate)
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

In [ ]:
# Unsupervised Learning Techniques
# 1. K-Means Clustering
# 2. Hierarchical Clustering
# Application: Customer Segmentation

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.datasets import make_blobs

# ---------------------------------------------------
# CREATE DATASET
# ---------------------------------------------------

# Generate customer dataset
# Features:
# [Annual Income, Spending Score]

X, y = make_blobs(
    n_samples=100,
    centers=3,
    cluster_std=1.5,
    random_state=42
)

# ---------------------------------------------------
# K-MEANS CLUSTERING
# ---------------------------------------------------

print("----- K-Means Clustering -----")

# Create K-Means model
kmeans = KMeans(n_clusters=3, random_state=42)

# Train model
kmeans.fit(X)

# Cluster labels
kmeans_labels = kmeans.labels_

# Cluster centers
centers = kmeans.cluster_centers_

print("Cluster Labels:")
print(kmeans_labels)

print("\nCluster Centers:")
print(centers)

# Plot K-Means Clusters
plt.figure(figsize=(6,5))

plt.scatter(
    X[:,0],
    X[:,1],
    c=kmeans_labels
)

plt.scatter(
    centers[:,0],
    centers[:,1],
    marker='X',
    s=200,
    color='red'
)

plt.title("K-Means Clustering")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")

plt.show()

# ---------------------------------------------------
# HIERARCHICAL CLUSTERING
# ---------------------------------------------------

print("\n----- Hierarchical Clustering -----")

# Generate linkage matrix
linked = linkage(X, method='ward')

# Plot dendrogram
plt.figure(figsize=(10,5))

dendrogram(linked)

plt.title("Hierarchical Clustering Dendrogram")
plt.xlabel("Data Points")
plt.ylabel("Distance")

plt.show()

In [ ]:
# ============================================
# Week 13
# Text Analytics & Recommendation System
# Google Colab Compatible
# ============================================

import pandas as pd
import string
import nltk

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.corpus import stopwords

# Download only stopwords
nltk.download('stopwords')

# ============================================
# TEXT PREPROCESSING
# ============================================

print("----- Text Preprocessing -----")

# Sample text
text = "The movie was amazing, exciting, and full of action scenes!"

# Convert to lowercase
text = text.lower()

# Remove punctuation
text = text.translate(str.maketrans('', '', string.punctuation))

# Tokenization using split()
tokens = text.split()

# Remove stopwords
stop_words = set(stopwords.words('english'))
filtered_tokens = [word for word in tokens if word not in stop_words]

print("\nOriginal Text:")
print("The movie was amazing, exciting, and full of action scenes!")

print("\nProcessed Tokens:")
print(filtered_tokens)

# ============================================
# CONTENT-BASED RECOMMENDATION SYSTEM
# ============================================

print("\n----- Content-Based Recommendation -----")

# Movie Dataset
movies = pd.DataFrame({
    'Movie': [
        'Avengers',
        'Batman',
        'Superman',
        'Titanic',
        'Inception'
    ],
    'Description': [
        'action superhero marvel fight',
        'dark superhero action detective',
        'superhero flying action hero',
        'romance ship love drama',
        'dream science fiction thriller'
    ]
})

print("\nMovie Dataset:")
print(movies)

# Convert descriptions into TF-IDF vectors
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(movies['Description'])

# Compute cosine similarity
similarity = cosine_similarity(tfidf_matrix)

# Movie for recommendation
movie_name = "Batman"

# Get movie index
movie_index = movies[movies['Movie'] == movie_name].index[0]

# Similarity scores
scores = list(enumerate(similarity[movie_index]))

# Sort scores
sorted_scores = sorted(scores, key=lambda x: x[1], reverse=True)

print("\nRecommended Movies for", movie_name + ":")

# Display top 3 recommendations
for i in sorted_scores[1:4]:
    print(movies.iloc[i[0]]['Movie'])