In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
N=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(N[0,2:4])
p=np.array([[1,2,3,4,5,6],[6,7,8,9,3,2]])
print(N[0,2:5])

[3 4]
[3 4 5]


In [ ]:
n=np.array([4,2,3,4])
p=np.where(n==4)
print(p)

(array([0, 3]),)
