In [ ]:
import numpy as np
a=np.array([10,12,13,14])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)
print(type(a))

[[1 2 3]
 [4 5 6]]
2
<class 'numpy.ndarray'>


In [4]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a[0,2:4])

[3 4]
